version: "3.8"

services:
  # Nginx servers
  nginx-backend:
    image: nginx
    container_name: prestabanco-nginx-backend-container
    restart: always
    ports:
      - 80:80
    volumes:
      - ./backend.conf:/etc/nginx/nginx.conf
    networks:
      - prestabanco-backend-network
    depends_on:
      - spring1
      - spring2
      - spring3

  nginx-frontend:
    image: nginx
    container_name: prestabanco-nginx-frontend-container
    restart: always
    ports:
      - 8070:8070
    volumes:
      - ./frontend.conf:/etc/nginx/nginx.conf
    networks:
      - prestabanco-frontend-network
    depends_on:
      - react1
      - react2
      - react3

  mysql:
    container_name: prestabanco-mysql-container
    image: mysql:latest
    restart: always
    volumes:
      - prestabanco-mysql-volume:/var/lib/mysql  # Ruta correcta
    networks:
      - prestabanco-backend-network
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=prestabanco
      - MYSQL_USER=amalia
      - MYSQL_PASSWORD=1234

  # Backend services
  spring1:
    container_name: prestabanco-backend-container-1
    image: maliviaux/prestabanco-backend:latest  # Cambia a backend si es necesario
    ports:
      - 8091:8090
    environment:
      DB_HOST: prestabanco-mysql-container
      DB_PORT: 3306
      DB_USERNAME: amalia
      DB_PASSWORD: 1234
    networks:
      - prestabanco-backend-network
    restart: always
    depends_on:
      - mysql

  spring2:
    container_name: prestabanco-backend-container-2
    image: maliviaux/prestabanco-backend:latest  # Cambia a backend si es necesario
    ports:
      - 8092:8090
    environment:
      DB_HOST: prestabanco-mysql-container
      DB_PORT: 3306
      DB_USERNAME: amalia
      DB_PASSWORD: 1234
    networks:
      - prestabanco-backend-network
    restart: always
    depends_on:
      - mysql

  spring3:
    container_name: prestabanco-backend-container-3
    image: maliviaux/prestabanco-backend:latest  # Cambia a backend si es necesario
    ports:
      - 8093:8090
    environment:
      DB_HOST: prestabanco-mysql-container
      DB_PORT: 3306
      DB_USERNAME: amalia
      DB_PASSWORD: 1234
    networks:
      - prestabanco-backend-network
    restart: always
    depends_on:
      - mysql

  # Frontend services
  react1:
    container_name: prestabanco-frontend-container-1
    image: maliviaux/prestabanco-frontend:latest
    ports:
      - 3001:3000
    networks:
      - prestabanco-frontend-network
    restart: always

  react2:
    container_name: prestabanco-frontend-container-2
    image: maliviaux/prestabanco-frontend:latest
    ports:
      - 3002:3000
    networks:
      - prestabanco-frontend-network
    restart: always

  react3:
    container_name: prestabanco-frontend-container-3
    image: maliviaux/prestabanco-frontend:latest
    ports:
      - 3003:3000
    networks:
      - prestabanco-frontend-network
    restart: always

volumes:
  prestabanco-mysql-volume:

networks:
  prestabanco-frontend-network:
  prestabanco-backend-network: